### ISSUE TITLE
RHEL failing at NPM install

### ISSUE THREAD

**Issue by ogardatadude** [PaloAltoNetworks/minemeld-ansible#13]
The RHEL ansible script is failing at task npm install

Any pointers on what might be the issue? Any other logs to look at? Posted below is all I have been able to locate and it doesn't tell me much as far as I can tell.

from the npm-debug.log:

8268 info install phantomjs@1.9.20
8269 verbose unsafe-perm in lifecycle false
8270 info phantomjs@1.9.20 Failed to exec install script
8271 verbose unlock done using /root/.npm/_locks/phantomjs-6ffbf2150425e594.lock for /opt/minemeld/www/webui/node_modules/phantomjs
8272 verbose stack Error: phantomjs@1.9.20 install: `node install.js`
8272 verbose stack Exit status 1
8272 verbose stack     at EventEmitter.<anonymous> (/opt/minemeld/www/venv/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
8272 verbose stack     at EventEmitter.emit (events.js:110:17)
8272 verbose stack     at ChildProcess.<anonymous> (/opt/minemeld/www/venv/lib/node_modules/npm/lib/utils/spawn.js:14:12)
8272 verbose stack     at ChildProcess.emit (events.js:110:17)
8272 verbose stack     at maybeClose (child_process.js:1015:16)
8272 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
8273 verbose pkgid phantomjs@1.9.20
8274 verbose cwd /opt/minemeld/www/webui
8275 error Linux 3.10.0-514.16.1.el7.x86_64
8276 error argv "/opt/minemeld/www/venv/bin/node" "/opt/minemeld/www/venv/bin/npm" "install"
8277 error node v0.12.2
8278 error npm  v2.7.4
8279 error code ELIFECYCLE
8280 error phantomjs@1.9.20 install: `node install.js`
8280 error Exit status 1
8281 error Failed at the phantomjs@1.9.20 install script 'node install.js'.
8281 error This is most likely a problem with the phantomjs package,
8281 error not with npm itself.
8281 error Tell the author that this fails on your system:
8281 error     node install.js
8281 error You can get their info via:
8281 error     npm owner ls phantomjs
8281 error There is likely additional logging output above.

**Comment by jtschichold** [comment]
Could you try installing bzip2 (sudo yum install bzip2) and relaunching the ansible playbook ?

**Comment by plarkin23** [comment]
I had a lot of issues getting NPM installed as well.  I could install it manually, but the ansible-playbook would constantly error out.  I also tried on my Ubuntu 16.4 image that I used in my lab without issue and that failed as well.

It turns out that you need to make sure that TCP/22 (app=ssh) and TCP/9418 (app=github-base, git-base) are permitted out to the Internet.  I did not have either port/application permitted which was causing my install failure @npm.

**Comment by rockycolttumtum** [comment]
Having issues with NPM Install on CentOs 7. I get the following error

Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git@github.com:mozilla/npm-lockdown.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-0d578943
ssh_exchange_identification: read: Connection timed out
fatal: Could not read from remote repository.

**Comment by jtschichold** [comment]
Hi @rockycolttumtum,
as @plarkin23, is ssh allowed by your firewall ? Otherwise you should set git config to force git on https.

**Comment by jtschichold** [comment]
Closing for no activity.
