### ISSUE TITLE
node-sass and node compatibility with workaround

### ISSUE THREAD

**Issue by pe3zx** [PaloAltoNetworks/minemeld-ansible#18]
`npm install` failed with this error.

```
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["npm", "install"], "delta": "0:04:22.804518", "end": "2017-09-20 11:20:24.476712", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-09-20 11:16:01.672194", "s
tderr": "npm WARN package.json minemeldWebui@0.9.42 No repository field.\nnpm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css\nnpm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (htt
ps://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.\nnpm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more in
formation\nnpm WARN deprecated bower@1.7.9: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD p
rojects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467\nnpm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no\nnpm WARN peerDepend
encies longer be automatically installed to fulfill the peerDependency \nnpm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2
or higher to avoid a RegExp DoS issue\nnpm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\nnpm WARN depr
ecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0
as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.\nnpm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130\nnpm WARN deprecated minimatch@0.2.14: Please up
date to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls
graceful-fs' to find it in the tree.\nnpm WARN engine browser-sync-client@2.5.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine request@2.81.0: wanted: {\"node\":\">= 4\"} (current: {\"
node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated node-uuid@1.4.7: Use uuid module instead\nnpm WARN engine esprima@4.0
.0: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine har-validator@4.2.1: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN optional dep failed, continui
ng fsevents@1.1.2\nnpm WARN optional dep failed, continuing fsevents@1.1.2\nnpm WARN optional dep failed, continuing fsevents@1.1.2\nnpm WARN engine har-schema@1.0.5: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.
7.4\"})\nnpm WARN engine request@2.82.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine har-validator@5.0.3: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\n
npm WARN engine hawk@6.0.2: wanted: {\"node\":\">=4.5.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine sntp@2.0.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine
 boom@4.3.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine cryptiles@3.1.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine hoek@4.2.
0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine boom@5.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN engine har-schema@2.0.0: wanted
: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\nnpm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated express@2.5.11: express 2.x series
is deprecated\nnpm WARN deprecated connect@1.9.2: connect 1.x series is deprecated\nnpm WARN engine xmlbuilder@9.0.4: wanted: {\"node\":\">=4.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})\n/opt/minemeld/www/webui/node_modules/g
ulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5\nconst Hoek = require('hoek');\n^^^^^\nSyntaxError: Use of const in strict mode.\n    at exports.runInThisContext (vm.js:73:16)\n
at Module._compile (module.js:443:25)\n    at Object.Module._extensions..js (module.js:478:10)\n    at Module.load (module.js:355:32)\n    at Function.Module._load (module.js:310:12)\n    at Module.require (module.js:365:17)\n    at requ
ire (module.js:384:17)\n    at Object.<anonymous> (/opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)\n    at Module._compile (module.js:460:26)\n    at Object.
Module._extensions..js (module.js:478:10)\nnpm ERR! Linux 4.4.0-96-generic\nnpm ERR! argv \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/bin/npm\" \"install\"\nnpm ERR! node v0.12.2\nnpm ERR! npm  v2.7.4\nnpm ERR! code ELIF
ECYCLE\n\nnpm ERR! node-sass@3.13.1 install: `node scripts/install.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.\nnpm ERR! This is most likely a problem with the
 node-sass package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     node scripts/install.js\nnpm ERR! You can get their info via:\nnpm ERR!     npm owner ls node-sass\nnpm ERR! There
 is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /opt/minemeld/www/webui/npm-debug.log", "stderr_lines": ["npm WARN package.json minemeldWebui@0.9.42 No rep
ository field.", "npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css", "npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any op
erations you were using wrench for. Thanks for all the usage over the years.", "npm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more information", "npm WARN deprecated bower@1.7.9: ..psst
! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but
please help to create it: https://github.com/bower/bower/issues/2467", "npm WARN peerDependencies The peer dependency jasmine-core@* included from karma-jasmine will no", "npm WARN peerDependencies longer be automatically installed to fu
lfill the peerDependency ", "npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.", "npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "n
pm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm", "npm WARN deprecated node-uuid@1.4.8: Use uuid module instead", "npm WARN deprecated minimatch@1.0.0: Please updat
e to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls g
raceful-fs' to find it in the tree.", "npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130", "npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or hig
her to avoid a RegExp DoS issue", "npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in t
he tree.", "npm WARN engine browser-sync-client@2.5.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine request@2.81.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\
":\"2.7.4\"})", "npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated node-uuid@1.4.7: Use uuid module instead", "npm WARN engine esprima@4.0.0: wanted: {\"nod
e\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine har-validator@4.2.1: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN optional dep failed, continuing fsevents@1.
1.2", "npm WARN optional dep failed, continuing fsevents@1.1.2", "npm WARN optional dep failed, continuing fsevents@1.1.2", "npm WARN engine har-schema@1.0.5: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})"
, "npm WARN engine request@2.82.0: wanted: {\"node\":\">= 4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine har-validator@5.0.3: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "np
m WARN engine hawk@6.0.2: wanted: {\"node\":\">=4.5.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine sntp@2.0.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engi
ne boom@4.3.1: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine cryptiles@3.1.2: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine hoe
k@4.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine boom@5.2.0: wanted: {\"node\":\">=4.0.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN engine har-schema@2.0
.0: wanted: {\"node\":\">=4\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN deprecated express@2.5.11: expre
ss 2.x series is deprecated", "npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated", "npm WARN engine xmlbuilder@9.0.4: wanted: {\"node\":\">=4.0\"} (current: {\"node\":\"0.12.2\",\"npm\":\"2.7.4\"})", "/opt/minemeld/www/
webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5", "const Hoek = require('hoek');", "^^^^^", "SyntaxError: Use of const in strict mode.", "    at exports.runInThi
sContext (vm.js:73:16)", "    at Module._compile (module.js:443:25)", "    at Object.Module._extensions..js (module.js:478:10)", "    at Module.load (module.js:355:32)", "    at Function.Module._load (module.js:310:12)", "    at Module.r
equire (module.js:365:17)", "    at require (module.js:384:17)", "    at Object.<anonymous> (/opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)", "    at Module
._compile (module.js:460:26)", "    at Object.Module._extensions..js (module.js:478:10)", "npm ERR! Linux 4.4.0-96-generic", "npm ERR! argv \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/bin/npm\" \"install\"", "npm ERR! no
de v0.12.2", "npm ERR! npm  v2.7.4", "npm ERR! code ELIFECYCLE", "", "npm ERR! node-sass@3.13.1 install: `node scripts/install.js`", "npm ERR! Exit status 1", "npm ERR! ", "npm ERR! Failed at the node-sass@3.13.1 install script 'node scr
ipts/install.js'.", "npm ERR! This is most likely a problem with the node-sass package,", "npm ERR! not with npm itself.", "npm ERR! Tell the author that this fails on your system:", "npm ERR!     node scripts/install.js", "npm ERR! You
can get their info via:", "npm ERR!     npm owner ls node-sass", "npm ERR! There is likely additional logging output above.", "", "npm ERR! Please include the following file with any support request:", "npm ERR!     /opt/minemeld/www/web
ui/npm-debug.log"], "stdout": "\n> deasync@0.1.1 install /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync\n> node ./build.js\n\n`linux-x64-node-0.12` exists; testing\nBinary is fine; exiting\n\n> phanto
mjs@1.9.20 install /opt/minemeld/www/webui/node_modules/phantomjs\n> node install.js\n\nPhantomJS not found on PATH\nDownloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2\nSaving t
o /opt/minemeld/www/webui/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2\nReceiving...\n\nReceived 12854K total.\nExtracting tar contents (via spawned process)\nRemoving /opt/minemeld/www/webui/node_modules/phantom
js/lib/phantom\nCopying extracted folder /opt/minemeld/www/webui/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1505906393708/phantomjs-1.9.8-linux-x86_64 -> /opt/minemeld/www/webui/node_modules/phantomjs/l
ib/phantom\nWriting location.js file\nDone. Phantomjs binary available at /opt/minemeld/www/webui/node_modules/phantomjs/lib/phantom/bin/phantomjs\n\n> node-sass@3.13.1 install /opt/minemeld/www/webui/node_modules/gulp-sass/node_modules/
node-sass\n> node scripts/install.js\n\n\n> bufferutil@1.2.1 install /opt/minemeld/www/webui/node_modules/gulp-protractor/node_modules/protractor/node_modules/selenium-webdriver/node_modules/ws/node_modules/bufferutil\n> node-gyp rebuild
```

This is content from `npm-debug.log`

```
218333 error Linux 4.4.0-96-generic
218334 error argv "/opt/minemeld/www/venv/bin/node" "/opt/minemeld/www/venv/bin/npm" "install"
218335 error node v0.12.2
218336 error npm  v2.7.4
218337 error code ELIFECYCLE
218338 error node-sass@3.13.1 install: `node scripts/install.js`
218338 error Exit status 1
218339 error Failed at the node-sass@3.13.1 install script 'node scripts/install.js'.
218339 error This is most likely a problem with the node-sass package,
218339 error not with npm itself.
218339 error Tell the author that this fails on your system:
218339 error     node scripts/install.js
218339 error You can get their info via:
218339 error     npm owner ls node-sass
218339 error There is likely additional logging output above.
```

Changing `node` version in `nodeenv` (`roles/minemeld/tasks/webui.yml`) to more recent version (e.g.  `nodeenv -v -n 6.11.3...`) can fix this issue. Please let me know if this is the correct solution for the issue, so I can create pull request to the project.

**Comment by jtschichold** [comment]
Thanks @pe3zx, I used your suggestion and moved to NPM 4.2.6 for consistency with the current Travis-CI building instructions in minemeld-webui
