### ISSUE TITLE
playbook Fails on RHEL 7.4 with deasync error during npm install

### ISSUE THREAD

**Issue by laskdesd** [PaloAltoNetworks/minemeld-ansible#34]
**Output from playbook:**

TASK [minemeld : npm install] 

fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["npm", "install"], "delta": "0:00:03.911678", "end": "2018-03-09 16:40:25.896891", "msg": "non-zero return code", "rc": 1, "start": "2018-03-09 16:40:21.985213", "stderr": "npm WARN package.json minemeldWebui@0.9.44 No repository field.\nnpm WARN package.json minemeldWebui@0.9.44 No license field.\nnpm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm\nnpm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\ngyp WARN EACCES user \"root\" does not have permission to access the dev dir \"/root/.node-gyp/4.2.6\"\ngyp WARN EACCES attempting to reinstall using temporary dev dir \"/opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync/.node-gyp\"\ngyp WARN install got an error, rolling back install\ngyp WARN install got an error, rolling back install\ngyp ERR! configure error \ngyp ERR! stack Error: unable to get local issuer certificate\ngyp ERR! stack     at Error (native)\ngyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)\ngyp ERR! stack     at emitNone (events.js:67:13)\ngyp ERR! stack     at TLSSocket.emit (events.js:166:7)\ngyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:585:8)\ngyp ERR! System Linux 3.10.0-693.el7.x86_64\ngyp ERR! command \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp ERR! cwd /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync\ngyp ERR! node -v v4.2.6\ngyp ERR! node-gyp -v v3.0.3\ngyp ERR! not ok \nBuild failed\nnpm ERR! Linux 3.10.0-693.el7.x86_64\nnpm ERR! argv \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/bin/npm\" \"install\"\nnpm ERR! node v4.2.6\nnpm ERR! npm  v2.14.12\nnpm ERR! code ELIFECYCLE\n\nnpm ERR! deasync@0.1.1 install: `node ./build.js`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the deasync@0.1.1 install script 'node ./build.js'.\nnpm ERR! This is most likely a problem with the deasync package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     node ./build.js\nnpm ERR! You can get their info via:\nnpm ERR!     npm owner ls deasync\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /opt/minemeld/www/webui/npm-debug.log", "stderr_lines": ["npm WARN package.json minemeldWebui@0.9.44 No repository field.", "npm WARN package.json minemeldWebui@0.9.44 No license field.", "npm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm", "npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js", "gyp WARN EACCES user \"root\" does not have permission to access the dev dir \"/root/.node-gyp/4.2.6\"", "gyp WARN EACCES attempting to reinstall using temporary dev dir \"/opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync/.node-gyp\"", "gyp WARN install got an error, rolling back install", "gyp WARN install got an error, rolling back install", "gyp ERR! configure error ", "gyp ERR! stack Error: unable to get local issuer certificate", "gyp ERR! stack     at Error (native)", "gyp ERR! stack     at TLSSocket.<anonymous> (_tls_wrap.js:1016:38)", "gyp ERR! stack     at emitNone (events.js:67:13)", "gyp ERR! stack     at TLSSocket.emit (events.js:166:7)", "gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:585:8)", "gyp ERR! System Linux 3.10.0-693.el7.x86_64", "gyp ERR! command \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"", "gyp ERR! cwd /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync", "gyp ERR! node -v v4.2.6", "gyp ERR! node-gyp -v v3.0.3", "gyp ERR! not ok ", "Build failed", "npm ERR! Linux 3.10.0-693.el7.x86_64", "npm ERR! argv \"/opt/minemeld/www/venv/bin/node\" \"/opt/minemeld/www/venv/bin/npm\" \"install\"", "npm ERR! node v4.2.6", "npm ERR! npm  v2.14.12", "npm ERR! code ELIFECYCLE", "", "npm ERR! deasync@0.1.1 install: `node ./build.js`", "npm ERR! Exit status 1", "npm ERR! ", "npm ERR! Failed at the deasync@0.1.1 install script 'node ./build.js'.", "npm ERR! This is most likely a problem with the deasync package,", "npm ERR! not with npm itself.", "npm ERR! Tell the author that this fails on your system:", "npm ERR!     node ./build.js", "npm ERR! You can get their info via:", "npm ERR!     npm owner ls deasync", "npm ERR! There is likely additional logging output above.", "", "npm ERR! Please include the following file with any support request:", "npm ERR!     /opt/minemeld/www/webui/npm-debug.log"], "stdout": "\n> deasync@0.1.1 install /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync\n> node ./build.js", "stdout_lines": ["", "> deasync@0.1.1 install /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync", "> node ./build.js"]}
        to retry, use: --limit @/home/mmeld/minemeld-ansible/local.retry

PLAY RECAP 
127.0.0.1                  : ok=61   changed=7    unreachable=0    failed=1

**npm-debug.log snippet:**

4221 info deasync@0.1.1 Failed to exec install script
4222 verbose unlock done using /root/.npm/_locks/deasync-ec18d7ac9941bff5.lock for /opt/minemeld/www/webui/node_modules/awesome-typescript-loader/node_modules/deasync
4223 verbose about to build /opt/minemeld/www/webui/node_modules/awesome-typescript-loader
4224 verbose unlock done using /root/.npm/_locks/awesome-typescript-loade-71d9a1c128d50641.lock for /opt/minemeld/www/webui/node_modules/awesome-typescript-loader
4225 verbose stack Error: deasync@0.1.1 install: `node ./build.js`
4225 verbose stack Exit status 1
4225 verbose stack     at EventEmitter.<anonymous> (/opt/minemeld/www/venv/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
4225 verbose stack     at emitTwo (events.js:87:13)
4225 verbose stack     at EventEmitter.emit (events.js:172:7)
4225 verbose stack     at ChildProcess.<anonymous> (/opt/minemeld/www/venv/lib/node_modules/npm/lib/utils/spawn.js:24:14)
4225 verbose stack     at emitTwo (events.js:87:13)
4225 verbose stack     at ChildProcess.emit (events.js:172:7)
4225 verbose stack     at maybeClose (internal/child_process.js:821:16)
4225 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
4226 verbose pkgid deasync@0.1.1
4227 verbose cwd /opt/minemeld/www/webui
4228 error Linux 3.10.0-693.el7.x86_64
4229 error argv "/opt/minemeld/www/venv/bin/node" "/opt/minemeld/www/venv/bin/npm" "install"
4230 error node v4.2.6
4231 error npm  v2.14.12
4232 error code ELIFECYCLE
4233 error deasync@0.1.1 install: `node ./build.js`
4233 error Exit status 1
4234 error Failed at the deasync@0.1.1 install script 'node ./build.js'.
4234 error This is most likely a problem with the deasync package,
4234 error not with npm itself.
4234 error Tell the author that this fails on your system:
4234 error     node ./build.js
4234 error You can get their info via:
4234 error     npm owner ls deasync
4234 error There is likely additional logging output above.

**Comment by jtschichold** [comment]
Hi @laskdesd,
have you tried again after this error?

**Comment by vlo001** [comment]
I'm having the same issue on Redhat 7.5. Is there a workaround for the issue?

**Comment by vlo001** [comment]
We decided to implement Minemeld on Ubuntu. The Ansible playbooks worked without any issues.

Thanks,
Vicki

**Comment by dnogu** [comment]
I'm having this issue with centos7 as of today.  Are there any workarounds available?

Thanks,

**Comment by vlo001** [comment]
We went with Ubuntu 16.04.5 and the installation completed without any issues.
