### ISSUE TITLE
[NPM Install: Failed] Ubuntu 18 Install issue

### ISSUE THREAD

**Issue by GuilleAbad** [PaloAltoNetworks/minemeld-ansible#67]
Hello everyone, I've tried to install minemeld ansible using the Ubuntu 18 HowTo and got the following error while running the ansible-playbook command:

TASK [minemeld : npm install] ***************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["npm", "install"], "delta": "0:07:22.230916", "end": "2019-04-11 11:59:29.597749", "msg": "non-z    ero return code", "rc": -9, "start": "2019-04-11 11:52:07.366833", "stderr": "npm WARN addRemoteGit Error: Command failed: git config --get remote.origin    .url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)\nnpm WARN addRemoteGit     at emitTwo (even    ts.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:1    6)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGit     at emitOne (events.js:96:13)\nnpm WARN     addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)\nnpm WARN addRemoteGit      mozilla/npm-lockdown#v0.0.8 resetting remote /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475 because of error: { Error: C    ommand failed: git config --get remote.origin.url\nnpm WARN addRemoteGit \nnpm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12    )\nnpm WARN addRemoteGit     at emitTwo (events.js:106:13)\nnpm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)\nnpm WARN addRemoteGit     a    t maybeClose (internal/child_process.js:920:16)\nnpm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)\nnpm WARN addRemoteGi    t     at emitOne (events.js:96:13)\nnpm WARN addRemoteGit     at Socket.emit (events.js:188:7)\nnpm WARN addRemoteGit     at Pipe._handle.close [as _oncl    ose] (net.js:509:12)\nnpm WARN addRemoteGit   killed: false,\nnpm WARN addRemoteGit   code: 1,\nnpm WARN addRemoteGit   signal: null,\nnpm WARN addRemote    Git   cmd: 'git config --get remote.origin.url' }\nnpm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more     information\nnpm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css\nnpm WARN deprecated bower@1.8.8: We don't recommend using Bower for n    ew projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-    from-bower/\nnpm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-c    a3b1f9f9ac5\nnpm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for     any operations you were using wrench for. Thanks for all the usage over the years.\nnpm WARN deprecated nsp@2.4.0: The Node Security Platform service is     shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting\nnpm WARN deprecated wreck@6.3.0: This vers    ion has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug     fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN depr    ecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to     get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im    /commercial).\nnpm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upg    rade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is availabl    e for older versions (hapi.im/commercial).\nnpm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy     (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this t    ime, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated topo@1.1.0: This version has been deprecated in accordance w    ith the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are     unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated tough-cookie@2.2.2: ReDoS vulner    ability parsing Set-Cookie https://nodesecurity.io/advisories/130\nnpm WARN deprecated node-uuid@1.4.7: Use uuid module instead\nnpm WARN deprecated mini    match@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated is-my-json-valid@2.13.1: catastrophic backtracki    ng in regexes could potentially lead to REDOS attack, upgrade to 2.17.2 as soon as possible\nnpm WARN deprecated cryptiles@2.0.5: This version has been d    eprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and sec    urity patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm ERR! git clone --templa    te=/root/.npm/_git-remotes/_templates --mirror git://github.com/mozilla/npm-lockdown.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-    v0-0-8-5edd5475: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475'...\nnpm ERR! git clone --    template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mozilla/npm-lockdown.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdow    n-git-v0-0-8-5edd5475: fatal: unable to connect to github.com:\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.co    m/mozilla/npm-lockdown.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475: github.com[0: 140.82.118.4]: errno=Connection     timed out\nnpm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mozilla/npm-lockdown.git /root/.npm/_git-remotes/g    it-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475: github.com[1: 140.82.118.3]: errno=Connection timed out\nnpm WARN deprecated express@2.5.11: expr    ess 2.x series is deprecated\nnpm WARN deprecated connect@1.9.2: connect 1.x series is deprecated\nnpm WARN deprecated formidable@1.0.17: Old versions of     Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.    2 or higher to avoid a RegExp DoS issue", "stderr_lines": ["npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url", "npm WARN a    ddRemoteGit ", "npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:199:12)", "npm WARN addRemoteGit     at emitTwo (events.js:106:13    )", "npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)", "npm WARN addRemoteGit     at maybeClose (internal/child_process.js:920:16)", "np    m WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)", "npm WARN addRemoteGit     at emitOne (events.js:96:13)", "npm WARN ad    dRemoteGit     at Socket.emit (events.js:188:7)", "npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:509:12)", "npm WARN addRemoteGit      mozilla/npm-lockdown#v0.0.8 resetting remote /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475 because of error: { Error:     Command failed: git config --get remote.origin.url", "npm WARN addRemoteGit ", "npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:    199:12)", "npm WARN addRemoteGit     at emitTwo (events.js:106:13)", "npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)", "npm WARN addRem    oteGit     at maybeClose (internal/child_process.js:920:16)", "npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:351:11)", "npm     WARN addRemoteGit     at emitOne (events.js:96:13)", "npm WARN addRemoteGit     at Socket.emit (events.js:188:7)", "npm WARN addRemoteGit     at Pipe._ha    ndle.close [as _onclose] (net.js:509:12)", "npm WARN addRemoteGit   killed: false,", "npm WARN addRemoteGit   code: 1,", "npm WARN addRemoteGit   signal:     null,", "npm WARN addRemoteGit   cmd: 'git config --get remote.origin.url' }", "npm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM     @types -- see README for more information", "npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css", "npm WARN deprecated bower@1.8.8: We     don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower    .io/blog/2017/how-to-migrate-away-from-bower/", "npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at h    ttps://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5", "npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://gith    ub.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.", "npm WARN deprecated nsp@2.4.    0: The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting", "    npm WARN deprecated wreck@6.3.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the lat    est version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older ver    sions (hapi.im/commercial).", "npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/suppo    rt). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid supp    ort is available for older versions (hapi.im/commercial).", "npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hap    i support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to     upgrade at this time, paid support is available for older versions (hapi.im/commercial).", "npm WARN deprecated hoek@2.16.3: This version has been deprec    ated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security     patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).", "npm WARN deprecated topo@1.1.0    : This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best fea    tures, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).", "    npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130", "npm WARN deprecated node-uuid@1.    4.7: Use uuid module instead", "npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue", "npm WARN d    eprecated is-my-json-valid@2.13.1: catastrophic backtracking in regexes could potentially lead to REDOS attack, upgrade to 2.17.2 as soon as possible", "    npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the     latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older     versions (hapi.im/commercial).", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mozilla/npm-lockdown.git /r    oot/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475: Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-mozil    la-npm-lockdown-git-v0-0-8-5edd5475'...", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/mozilla/npm-lockdow    n.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475: fatal: unable to connect to github.com:", "npm ERR! git clone --te    mplate=/root/.npm/_git-remotes/_templates --mirror git://github.com/mozilla/npm-lockdown.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-    git-v0-0-8-5edd5475: github.com[0: 140.82.118.4]: errno=Connection timed out", "npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror     git://github.com/mozilla/npm-lockdown.git /root/.npm/_git-remotes/git-github-com-mozilla-npm-lockdown-git-v0-0-8-5edd5475: github.com[1: 140.82.118.3]:     errno=Connection timed out", "npm WARN deprecated express@2.5.11: express 2.x series is deprecated", "npm WARN deprecated connect@1.9.2: connect 1.x seri    es is deprecated", "npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or la    ter", "npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/minemeld-ansible/local.retry

PLAY RECAP **********************************************************************************************************************************************
127.0.0.1                  : ok=54   changed=9    unreachable=0    failed=1

Seems to have deprecated modules or repos inside the installation config. Any solution?

Thanks in advance!

**Comment by GuilleAbad** [comment]
Welcome again, I've solved ERR errors in that Task changing from git:// to https:// because of firewall restrictions. But that Task isnt already working succesfully. Using playbook-ansible -vvvv to debug the output, shows the following traceback:

fatal: [127.0.0.1]: FAILED! => {
    "changed": true,
    "cmd": [
        "npm",
        "install"
    ],
    "delta": "0:04:48.684882",
    "end": "2019-04-22 12:54:39.116461",
    "invocation": {
        "module_args": {
            "_raw_params": "npm install",
            "_uses_shell": false,
            "argv": null,
            "chdir": "/opt/minemeld/www/webui",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": -9,
    "start": "2019-04-22 12:49:50.431579",
    "stderr": "npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css\nnpm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5\nnpm WARN deprecated nsp@2.4.0: The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting\nnpm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.\nnpm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more information\nnpm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/\nnpm WARN deprecated wreck@6.3.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130\nnpm WARN deprecated node-uuid@1.4.7: Use uuid module instead\nnpm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated is-my-json-valid@2.13.1: catastrophic backtracking in regexes could potentially lead to REDOS attack, upgrade to 2.17.2 as soon as possible\nnpm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.\nnpm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).\nnpm WARN deprecated express@2.5.11: express 2.x series is deprecated\nnpm WARN deprecated connect@1.9.2: connect 1.x series is deprecated\nnpm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\nnpm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\nnpm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.\nnpm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header\nnpm WARN deprecated gulp-footer@1.1.2: Security vulnerability surrounding event-stream, do *NOT* use.\nnpm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.\nnpm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.\nnpm WARN deprecated node-uuid@1.4.8: Use uuid module instead\nnpm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm\nnpm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js",
    "stderr_lines": [
        "npm WARN deprecated gulp-minify-css@1.2.4: Please use gulp-clean-css",
        "npm WARN deprecated gulp-util@3.0.7: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5",
        "npm WARN deprecated nsp@2.4.0: The Node Security Platform service is shutting down 9/30 - https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting",
        "npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.",
        "npm WARN deprecated typings@0.8.1: Typings is deprecated in favor of NPM @types -- see README for more information",
        "npm WARN deprecated bower@1.8.8: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/",
        "npm WARN deprecated wreck@6.3.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).",
        "npm WARN deprecated joi@6.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).",
        "npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).",
        "npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).",
        "npm WARN deprecated topo@1.1.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).",
        "npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.",
        "npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130",
        "npm WARN deprecated node-uuid@1.4.7: Use uuid module instead",
        "npm WARN deprecated minimatch@3.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue",
        "npm WARN deprecated is-my-json-valid@2.13.1: catastrophic backtracking in regexes could potentially lead to REDOS attack, upgrade to 2.17.2 as soon as possible",
        "npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.",
        "npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).",
        "npm WARN deprecated express@2.5.11: express 2.x series is deprecated",
        "npm WARN deprecated connect@1.9.2: connect 1.x series is deprecated",
        "npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later",
        "npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue",
        "npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js",
        "npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue",
        "npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js",
        "npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.",
        "npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header",
        "npm WARN deprecated gulp-footer@1.1.2: Security vulnerability surrounding event-stream, do *NOT* use.",
        "npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.",
        "npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.",
        "npm WARN deprecated node-uuid@1.4.8: Use uuid module instead",
        "npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue",
        "npm WARN deprecated npmconf@1.1.5: this package has been reintegrated into npm and is now out of date with respect to npm",
        "npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js"
    ],
    "stdout": "",
    "stdout_lines": []
}
        to retry, use: --limit @/root/minemeld-ansible/local.retry

PLAY RECAP ************************************************************************************************************************************************
127.0.0.1                  : ok=54   changed=8    unreachable=0    failed=1

Any ideas? The installation is dealing with too much deprecated packages, and it seems to doesnt let the installation finish succesfully.

Thanks again!

**Comment by rraj1996** [comment]
Did you get any solution for this because i am facing the same issue.

**Comment by EdoardoMDP** [comment]
Hi @GuilleAbad  ,
Did you get any solution for this issue ?
because i am facing the same problem.

**Comment by nielsvbrecht** [comment]
For me it seemed to be fixed when i ensured i was on the latest npm version.
I used: sudo npm install -g npm@latest
